---
- name: Shorewall - Configure Shorewall IPv4
  ansible.builtin.include_tasks:
    file: shorewall.yml
  when: shorewall
  tags: shorewall

- name: Shorewall - Configure Shorewal IPv6
  ansible.builtin.include_tasks:
    file: shorewall6.yml
  when: shorewall6
  tags: ['shorewall', 'shorewall6']
