---
- name: Install Shorewall
  ansible.builtin.apt:
    name: shorewall
    state: present
  tags: shorewall
  register: result
  until: result is succeeded

- name: /etc/default/shorewall
  ansible.builtin.template:
    dest: /etc/default/shorewall
    src: default/shorewall.j2
    owner: root
    group: root
    mode: '0640'
  notify: shorewall_restart
  tags: shorewall

- name: Shorewall configuration files
  ansible.builtin.template:
    dest: "/etc/shorewall/{{ item }}"
    src: "shorewall/{{ item }}.j2"
    owner: root
    group: root
    mode: '0640'
  with_items:
    - interfaces
    - zones
    - policy
    - rules
    - snat
  notify: shorewall_restart
  tags: shorewall

- name: Shorewall main config
  ansible.builtin.template:
    dest: "/etc/shorewall/shorewall.conf"
    src: "shorewall/shorewall.conf.j2"
    owner: root
    group: root
    mode: '0640'
  notify: shorewall_restart
  tags: shorewall

- name: Start and enable the Shorewall service
  async: 30
  poll: 5
  ansible.builtin.service:
    name: shorewall
    state: started
    enabled: true
  tags: shorewall
