---
- name: Install Shorewall6
  ansible.builtin.apt:
    name: shorewall6
  tags: ['shorewall', 'shorewall6']
  register: result
  until: result is succeeded

- name: /etc/default/shorewall6
  ansible.builtin.template:
    dest: /etc/default/shorewall6
    src: default/shorewall6.j2
    owner: root
    group: root
    mode: '0640'
  notify: shorewall6_restart
  tags: ['shorewall', 'shorewall6']

- name: Shorewall6 configuration files
  ansible.builtin.template:
    dest: "/etc/shorewall6/{{ item }}"
    src: "shorewall6/{{ item }}.j2"
    owner: root
    group: root
    mode: '0640'
  with_items:
    - interfaces
    - zones
    - policy
    - rules
    - snat
  notify: shorewall6_restart
  tags: ['shorewall', 'shorewall6']

- name: Shorewall6 main config
  ansible.builtin.template:
    dest: "/etc/shorewall6/shorewall6.conf"
    src: "shorewall6/shorewall6.conf.j2"
    owner: root
    group: root
    mode: '0640'
  notify: shorewall6_restart
  tags: ['shorewall', 'shorewall6']

- name: Start and enable the Shorewall6 service
  async: 30
  poll: 5
  ansible.builtin.service:
    name: shorewall6
    state: started
    enabled: true
  tags: ['shorewall', 'shorewall6']
