---

- name: Shorewall - Restart Shorewall
  ansible.builtin.service:
    name: shorewall
    state: restarted
  become: true
  listen: shorewall_restart

- name: Shorewall - Restart Shorewall6
  ansible.builtin.service:
    name: shorewall6
    state: restarted
  become: true
  listen: shorewall6_restart
